services:
  - type: web
    name: study-planer
    runtime: node
    buildCommand: npm ci --prefix client && npm run build --prefix client && npm ci --prefix server
    startCommand: npm start --prefix server
    healthCheckPath: /health
