export const ONBOARDING_TOUR_EVENT = "planerka:start-onboarding-tour";
export const ONBOARDING_PENDING_KEY = "planerka:onboarding:pending";

const TOUR_TRANSLATIONS = {
  ru: {
    "Step": "Шаг",
    "of": "из",
    "Skip": "Пропустить",
    "Back": "Назад",
    "OK, next": "ОК, дальше",
    "Finish": "Готово",
    "Welcome tour": "Приветственный тур",
    "Replay tour": "Повторить тур",
    "Replay the first-time tutorial and highlights.": "Повторите вводный тур и подсказки.",
    "Welcome to PLANERKA": "Добро пожаловать в PLANERKA",
    "This is your home base. You can see what needs attention and jump into the work that matters today.": "Это ваша главная страница. Здесь видно, что требует внимания, и можно быстро перейти к важным делам на сегодня.",
    "Check your task pulse": "Проверьте состояние задач",
    "These cards show overdue work, today's tasks, weekly deadlines, and everything still open.": "Эти карточки показывают просроченные задачи, дела на сегодня, дедлайны недели и всё, что ещё открыто.",
    "Keep courses close": "Курсы всегда рядом",
    "Your most useful courses appear here so class details, notes, and schedules stay easy to reach.": "Здесь появляются важные курсы, чтобы детали занятий, заметки и расписание были под рукой.",
    "Use quick actions": "Используйте быстрые действия",
    "Start common workflows like creating courses, adding tasks, or opening the weekly planner.": "Отсюда удобно создавать курсы, добавлять задачи и открывать недельный планировщик.",
    "Watch your schedule": "Следите за расписанием",
    "Swipe or scroll to the schedule page to see courses, deadlines, and planned blocks together.": "Смахните или прокрутите к расписанию, чтобы увидеть курсы, дедлайны и запланированные блоки вместе.",
    "Build your courses": "Создавайте курсы",
    "Courses are where class times, colors, notes, and course-specific work begin.": "В курсах задаются время занятий, цвета, заметки и задачи по конкретному предмету.",
    "Capture tasks": "Добавляйте задачи",
    "Use Tasks to add assignments, set deadlines, attach files, and mark work as done.": "В задачах можно добавлять задания, ставить сроки, прикреплять файлы и отмечать выполненное.",
    "Plan the day": "Планируйте день",
    "Daily planning helps turn tasks and activities into a realistic schedule.": "Дневное планирование помогает превратить задачи и активности в реалистичное расписание.",
    "Work with chat": "Работайте в чате",
    "Chat keeps conversations and planning with classmates in the same workspace.": "Чат хранит общение и совместное планирование с однокурсниками в одном рабочем пространстве.",
    "Review progress": "Смотрите прогресс",
    "Statistics shows trends in your tasks and study flow so you can adjust before things pile up.": "Статистика показывает тенденции по задачам и учёбе, чтобы вы могли скорректировать план заранее.",
    "Replay anytime": "Повторите в любой момент",
    "You can restart this welcome tour from Settings whenever you want a quick refresher.": "Вы можете заново запустить этот тур из настроек, когда понадобится быстро освежить память.",
    "This bottom bar is your main mobile control center. Home brings you back to the dashboard.": "Нижняя панель — главный центр управления на телефоне. Home возвращает вас на панель.",
    "Check today fast": "Быстро проверьте день",
    "These numbers summarize overdue tasks, today's work, this week, and all open tasks.": "Эти числа показывают просрочки, работу на сегодня, дела недели и все открытые задачи.",
    "Open your courses": "Откройте курсы",
    "Your course shortcuts live here. Tap one to jump into notes, class times, and course tasks.": "Здесь находятся быстрые ссылки на курсы. Нажмите курс, чтобы открыть заметки, время занятий и задачи.",
    "Use mobile shortcuts": "Используйте мобильные ярлыки",
    "These buttons open quick course and action sheets without making you hunt around the page.": "Эти кнопки открывают быстрые панели курсов и действий без лишнего поиска по странице.",
    "Swipe to schedule": "Смахните к расписанию",
    "The dashboard slides sideways on mobile. Your schedule page shows courses, deadlines, and planned blocks.": "На телефоне панель листается вбок. Страница расписания показывает курсы, дедлайны и планы.",
    "Courses tab": "Вкладка курсов",
    "Courses is where you create classes, add colors, and keep class details organized.": "В курсах вы создаёте занятия, добавляете цвета и храните детали предметов.",
    "Chat tab": "Вкладка чата",
    "Chat keeps study conversations and planning with classmates close at hand.": "Чат держит учебные разговоры и планы с однокурсниками под рукой.",
    "Assistant tab": "Вкладка ассистента",
    "Assistant opens your study helper from anywhere on mobile.": "Ассистент открывает учебного помощника из любого места на телефоне.",
    "More menu": "Меню ещё",
    "Menu holds the rest of the app, including tasks, daily planning, statistics, and settings.": "В меню находятся остальные разделы: задачи, дневной план, статистика и настройки.",
    "Create tasks": "Создавайте задачи",
    "Use this button to capture assignments, due dates, files, and planned work time.": "Эта кнопка добавляет задания, сроки, файлы и запланированное время работы.",
    "Settings lets you restart this mobile tour whenever you want a refresher.": "В настройках можно снова запустить мобильный тур, когда понадобится подсказка."
  },
  ko: {
    "Step": "단계",
    "of": "/",
    "Skip": "건너뛰기",
    "Back": "뒤로",
    "OK, next": "확인, 다음",
    "Finish": "완료",
    "Welcome tour": "환영 투어",
    "Replay tour": "투어 다시 보기",
    "Replay the first-time tutorial and highlights.": "처음 사용자 안내와 하이라이트를 다시 봅니다.",
    "Welcome to PLANERKA": "PLANERKA에 오신 것을 환영합니다",
    "This is your home base. You can see what needs attention and jump into the work that matters today.": "여기는 홈 베이스입니다. 지금 필요한 일과 오늘 중요한 작업을 바로 확인할 수 있습니다.",
    "Check your task pulse": "작업 상태 확인",
    "These cards show overdue work, today's tasks, weekly deadlines, and everything still open.": "이 카드들은 지난 마감, 오늘 할 일, 이번 주 마감, 아직 열린 작업을 보여줍니다.",
    "Keep courses close": "강의를 가까이에",
    "Your most useful courses appear here so class details, notes, and schedules stay easy to reach.": "자주 쓰는 강의가 여기에 표시되어 세부 정보, 노트, 일정을 쉽게 열 수 있습니다.",
    "Use quick actions": "빠른 작업 사용",
    "Start common workflows like creating courses, adding tasks, or opening the weekly planner.": "강의 만들기, 작업 추가, 주간 플래너 열기 같은 흐름을 빠르게 시작합니다.",
    "Watch your schedule": "일정 확인",
    "Swipe or scroll to the schedule page to see courses, deadlines, and planned blocks together.": "스와이프하거나 스크롤해서 강의, 마감, 계획 블록을 한곳에서 확인하세요.",
    "Build your courses": "강의 만들기",
    "Courses are where class times, colors, notes, and course-specific work begin.": "강의에서는 수업 시간, 색상, 노트, 강의별 작업을 관리합니다.",
    "Capture tasks": "작업 추가",
    "Use Tasks to add assignments, set deadlines, attach files, and mark work as done.": "작업에서 과제 추가, 마감 설정, 파일 첨부, 완료 표시를 할 수 있습니다.",
    "Plan the day": "하루 계획",
    "Daily planning helps turn tasks and activities into a realistic schedule.": "일일 계획은 작업과 활동을 현실적인 일정으로 바꿔줍니다.",
    "Work with chat": "채팅으로 작업",
    "Chat keeps conversations and planning with classmates in the same workspace.": "채팅은 친구들과의 대화와 계획을 같은 공간에 보관합니다.",
    "Review progress": "진행 상황 보기",
    "Statistics shows trends in your tasks and study flow so you can adjust before things pile up.": "통계는 작업과 공부 흐름의 추세를 보여줘 일이 쌓이기 전에 조정할 수 있게 합니다.",
    "Replay anytime": "언제든 다시 보기",
    "You can restart this welcome tour from Settings whenever you want a quick refresher.": "설정에서 이 환영 투어를 언제든 다시 시작할 수 있습니다.",
    "This bottom bar is your main mobile control center. Home brings you back to the dashboard.": "아래 바는 모바일의 주요 컨트롤입니다. Home은 대시보드로 돌아갑니다.",
    "Check today fast": "오늘을 빠르게 확인",
    "These numbers summarize overdue tasks, today's work, this week, and all open tasks.": "이 숫자는 지난 마감, 오늘 작업, 이번 주, 열린 작업을 요약합니다.",
    "Open your courses": "강의 열기",
    "Your course shortcuts live here. Tap one to jump into notes, class times, and course tasks.": "강의 바로가기가 여기에 있습니다. 탭하면 노트, 수업 시간, 강의 작업으로 이동합니다.",
    "Use mobile shortcuts": "모바일 바로가기 사용",
    "These buttons open quick course and action sheets without making you hunt around the page.": "이 버튼들은 페이지를 헤매지 않고 강의와 작업 시트를 빠르게 엽니다.",
    "Swipe to schedule": "일정으로 스와이프",
    "The dashboard slides sideways on mobile. Your schedule page shows courses, deadlines, and planned blocks.": "모바일 대시보드는 옆으로 이동합니다. 일정 페이지에서 강의, 마감, 계획 블록을 봅니다.",
    "Courses tab": "강의 탭",
    "Courses is where you create classes, add colors, and keep class details organized.": "강의 탭에서 수업을 만들고 색상을 추가하며 세부 정보를 정리합니다.",
    "Chat tab": "채팅 탭",
    "Chat keeps study conversations and planning with classmates close at hand.": "채팅은 공부 대화와 친구들과의 계획을 가까이 둡니다.",
    "Assistant tab": "도우미 탭",
    "Assistant opens your study helper from anywhere on mobile.": "도우미는 모바일 어디서든 학습 도우미를 엽니다.",
    "More menu": "더보기 메뉴",
    "Menu holds the rest of the app, including tasks, daily planning, statistics, and settings.": "메뉴에는 작업, 일일 계획, 통계, 설정 등 나머지 기능이 있습니다.",
    "Create tasks": "작업 만들기",
    "Use this button to capture assignments, due dates, files, and planned work time.": "이 버튼으로 과제, 마감일, 파일, 계획 시간을 추가합니다.",
    "Settings lets you restart this mobile tour whenever you want a refresher.": "설정에서 모바일 투어를 언제든 다시 시작할 수 있습니다."
  },
  kk: {
    "Step": "Қадам",
    "of": "/",
    "Skip": "Өткізу",
    "Back": "Артқа",
    "OK, next": "Жарайды, келесі",
    "Finish": "Аяқтау",
    "Welcome tour": "Қош келдіңіз туры",
    "Replay tour": "Турды қайталау",
    "Replay the first-time tutorial and highlights.": "Алғашқы нұсқаулық пен бөлектелген кеңестерді қайта көріңіз.",
    "Welcome to PLANERKA": "PLANERKA-ға қош келдіңіз",
    "This is your home base. You can see what needs attention and jump into the work that matters today.": "Бұл сіздің негізгі бетіңіз. Мұнда маңызды нәрсені көріп, бүгінгі жұмысқа тез өте аласыз.",
    "Check your task pulse": "Тапсырма күйін тексеріңіз",
    "These cards show overdue work, today's tasks, weekly deadlines, and everything still open.": "Бұл карталар кешіккен жұмыстарды, бүгінгі тапсырмаларды, апта мерзімдерін және ашық істерді көрсетеді.",
    "Keep courses close": "Курстарды жақын ұстаңыз",
    "Your most useful courses appear here so class details, notes, and schedules stay easy to reach.": "Маңызды курстар осында тұрады, сондықтан сабақ мәліметі, жазбалар және кесте оңай ашылады.",
    "Use quick actions": "Жылдам әрекеттерді қолданыңыз",
    "Start common workflows like creating courses, adding tasks, or opening the weekly planner.": "Курс жасау, тапсырма қосу немесе апталық жоспарды ашу сияқты әрекеттерді тез бастаңыз.",
    "Watch your schedule": "Кестені бақылаңыз",
    "Swipe or scroll to the schedule page to see courses, deadlines, and planned blocks together.": "Курстарды, мерзімдерді және жоспарланған блоктарды бірге көру үшін кестеге сырғытыңыз.",
    "Build your courses": "Курстар жасаңыз",
    "Courses are where class times, colors, notes, and course-specific work begin.": "Курстарда сабақ уақыты, түстер, жазбалар және курс тапсырмалары басталады.",
    "Capture tasks": "Тапсырмалар қосыңыз",
    "Use Tasks to add assignments, set deadlines, attach files, and mark work as done.": "Тапсырмаларда жұмыс қосып, мерзім қойып, файл тіркеп, орындалғанын белгілей аласыз.",
    "Plan the day": "Күнді жоспарлаңыз",
    "Daily planning helps turn tasks and activities into a realistic schedule.": "Күндік жоспарлау тапсырмалар мен әрекеттерді нақты кестеге айналдырады.",
    "Work with chat": "Чатпен жұмыс істеңіз",
    "Chat keeps conversations and planning with classmates in the same workspace.": "Чат әңгімелер мен ортақ жоспарлауды бір жұмыс кеңістігінде сақтайды.",
    "Review progress": "Прогресті қараңыз",
    "Statistics shows trends in your tasks and study flow so you can adjust before things pile up.": "Статистика тапсырма мен оқу ағымын көрсетіп, бәрі жиналмай тұрып түзетуге көмектеседі.",
    "Replay anytime": "Кез келген уақытта қайталаңыз",
    "You can restart this welcome tour from Settings whenever you want a quick refresher.": "Бұл турды баптаулардан кез келген уақытта қайта бастай аласыз.",
    "This bottom bar is your main mobile control center. Home brings you back to the dashboard.": "Төменгі жолақ — мобильдегі негізгі басқару. Home сізді панельге қайтарады.",
    "Check today fast": "Бүгінді тез тексеріңіз",
    "These numbers summarize overdue tasks, today's work, this week, and all open tasks.": "Бұл сандар кешіккен, бүгінгі, апталық және барлық ашық тапсырмаларды қысқаша көрсетеді.",
    "Open your courses": "Курстарды ашыңыз",
    "Your course shortcuts live here. Tap one to jump into notes, class times, and course tasks.": "Курс жарлықтары осында. Біреуін бассаңыз, жазбаларға, сабақ уақытына және тапсырмаларға өтесіз.",
    "Use mobile shortcuts": "Мобильді жарлықтарды қолданыңыз",
    "These buttons open quick course and action sheets without making you hunt around the page.": "Бұл батырмалар беттен іздемей-ақ курс пен әрекет панельдерін ашады.",
    "Swipe to schedule": "Кестеге сырғытыңыз",
    "The dashboard slides sideways on mobile. Your schedule page shows courses, deadlines, and planned blocks.": "Мобильде панель жанға сырғиды. Кесте беті курстарды, мерзімдерді және жоспарларды көрсетеді.",
    "Courses tab": "Курстар қойындысы",
    "Courses is where you create classes, add colors, and keep class details organized.": "Курстарда сабақ жасап, түстер қосып, мәліметтерді реттейсіз.",
    "Chat tab": "Чат қойындысы",
    "Chat keeps study conversations and planning with classmates close at hand.": "Чат оқу әңгімелері мен жоспарларды қол астында ұстайды.",
    "Assistant tab": "Көмекші қойындысы",
    "Assistant opens your study helper from anywhere on mobile.": "Көмекші мобильде кез келген жерден оқу көмекшісін ашады.",
    "More menu": "Қосымша мәзір",
    "Menu holds the rest of the app, including tasks, daily planning, statistics, and settings.": "Мәзірде тапсырмалар, күндік жоспар, статистика және баптаулар бар.",
    "Create tasks": "Тапсырмалар жасаңыз",
    "Use this button to capture assignments, due dates, files, and planned work time.": "Бұл батырмамен тапсырма, мерзім, файл және жоспарланған уақыт қосасыз.",
    "Settings lets you restart this mobile tour whenever you want a refresher.": "Баптауларда бұл мобильді турды кез келген уақытта қайта бастауға болады."
  },
  uz: {
    "Step": "Qadam",
    "of": "/",
    "Skip": "O'tkazib yuborish",
    "Back": "Orqaga",
    "OK, next": "OK, keyingi",
    "Finish": "Tugatish",
    "Welcome tour": "Xush kelibsiz turi",
    "Replay tour": "Turni qayta ko'rish",
    "Replay the first-time tutorial and highlights.": "Birinchi qo'llanma va ajratilgan joylarni qayta ko'ring.",
    "Welcome to PLANERKA": "PLANERKAga xush kelibsiz",
    "This is your home base. You can see what needs attention and jump into the work that matters today.": "Bu sizning asosiy sahifangiz. Bu yerda e'tibor kerak ishlarni ko'rib, bugungi muhim vazifalarga o'tasiz.",
    "Check your task pulse": "Vazifalar holatini tekshiring",
    "These cards show overdue work, today's tasks, weekly deadlines, and everything still open.": "Bu kartalar kechikkan ishlar, bugungi vazifalar, haftalik muddatlar va ochiq ishlarni ko'rsatadi.",
    "Keep courses close": "Kurslarni yaqin tuting",
    "Your most useful courses appear here so class details, notes, and schedules stay easy to reach.": "Muhim kurslar shu yerda turadi, shunda dars tafsilotlari, yozuvlar va jadval tez ochiladi.",
    "Use quick actions": "Tez amallardan foydalaning",
    "Start common workflows like creating courses, adding tasks, or opening the weekly planner.": "Kurs yaratish, vazifa qo'shish yoki haftalik rejani ochishni tez boshlang.",
    "Watch your schedule": "Jadvalni kuzating",
    "Swipe or scroll to the schedule page to see courses, deadlines, and planned blocks together.": "Kurslar, muddatlar va rejalangan bloklarni birga ko'rish uchun jadval sahifasiga o'ting.",
    "Build your courses": "Kurslaringizni yarating",
    "Courses are where class times, colors, notes, and course-specific work begin.": "Kurslarda dars vaqti, ranglar, yozuvlar va kursga oid ishlar boshlanadi.",
    "Capture tasks": "Vazifalarni qo'shing",
    "Use Tasks to add assignments, set deadlines, attach files, and mark work as done.": "Vazifalarda topshiriq qo'shing, muddat belgilang, fayl biriktiring va bajarilganini belgilang.",
    "Plan the day": "Kunni rejalang",
    "Daily planning helps turn tasks and activities into a realistic schedule.": "Kunlik reja vazifa va faoliyatlarni real jadvalga aylantiradi.",
    "Work with chat": "Chat bilan ishlang",
    "Chat keeps conversations and planning with classmates in the same workspace.": "Chat suhbatlar va kursdoshlar bilan rejalarni bir ish joyida saqlaydi.",
    "Review progress": "Progressni ko'ring",
    "Statistics shows trends in your tasks and study flow so you can adjust before things pile up.": "Statistika vazifalar va o'qish oqimini ko'rsatib, ishlar yig'ilmasidan oldin tuzatishga yordam beradi.",
    "Replay anytime": "Istalgan payt qaytaring",
    "You can restart this welcome tour from Settings whenever you want a quick refresher.": "Bu turni Sozlamalardan istalgan payt qayta boshlashingiz mumkin.",
    "This bottom bar is your main mobile control center. Home brings you back to the dashboard.": "Pastki panel mobil boshqaruv markazi. Home sizni boshqaruv paneliga qaytaradi.",
    "Check today fast": "Bugunni tez tekshiring",
    "These numbers summarize overdue tasks, today's work, this week, and all open tasks.": "Bu raqamlar kechikkan, bugungi, haftalik va ochiq vazifalarni qisqa ko'rsatadi.",
    "Open your courses": "Kurslarni oching",
    "Your course shortcuts live here. Tap one to jump into notes, class times, and course tasks.": "Kurs yorliqlari shu yerda. Bosing va yozuvlar, dars vaqti, kurs vazifalariga o'ting.",
    "Use mobile shortcuts": "Mobil yorliqlardan foydalaning",
    "These buttons open quick course and action sheets without making you hunt around the page.": "Bu tugmalar sahifadan qidirmasdan kurs va amal panellarini tez ochadi.",
    "Swipe to schedule": "Jadvalga suring",
    "The dashboard slides sideways on mobile. Your schedule page shows courses, deadlines, and planned blocks.": "Mobil boshqaruv paneli yon tomonga suriladi. Jadval sahifasi kurslar, muddatlar va bloklarni ko'rsatadi.",
    "Courses tab": "Kurslar bo'limi",
    "Courses is where you create classes, add colors, and keep class details organized.": "Kurslarda dars yaratasiz, rang qo'shasiz va tafsilotlarni tartiblayasiz.",
    "Chat tab": "Chat bo'limi",
    "Chat keeps study conversations and planning with classmates close at hand.": "Chat o'qish suhbatlari va kursdoshlar bilan rejalarni yaqin tutadi.",
    "Assistant tab": "Yordamchi bo'limi",
    "Assistant opens your study helper from anywhere on mobile.": "Yordamchi mobilning istalgan joyidan o'quv yordamchisini ochadi.",
    "More menu": "Qo'shimcha menyu",
    "Menu holds the rest of the app, including tasks, daily planning, statistics, and settings.": "Menyuda vazifalar, kunlik reja, statistika va sozlamalar bor.",
    "Create tasks": "Vazifa yarating",
    "Use this button to capture assignments, due dates, files, and planned work time.": "Bu tugma topshiriq, muddat, fayl va rejalangan ish vaqtini qo'shadi.",
    "Settings lets you restart this mobile tour whenever you want a refresher.": "Sozlamalar mobil turni istalgan payt qayta boshlash imkonini beradi."
  }
};

export function translateOnboardingText(language, text) {
  return TOUR_TRANSLATIONS[language]?.[text] || text;
}
